version: "3.9"
services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: broker
      POSTGRES_USER: broker
      POSTGRES_PASSWORD: broker
    ports:
      - "5432:5432"

  api:
    build: .
    command: uvicorn backend.api:app --host 0.0.0.0 --port 8000
    environment:
      USE_DB: "true"
      DATABASE_URL: postgresql://broker:broker@db:5432/broker
      OPENAI_API_KEY: ${OPENAI_API_KEY-}
    ports:
      - "8000:8000"
    depends_on:
      - db

  app:
    build: .
    command: streamlit run app/main.py --server.port 8501 --server.address 0.0.0.0
    environment:
      API_BASE_URL: http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
